apiVersion: v1
kind: Namespace
metadata:
  name: cloudops
  labels:
    name: cloudops
    app.kubernetes.io/name: cloudops-dashboard
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: cloudops-platform
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudops-staging
  labels:
    name: cloudops-staging
    app.kubernetes.io/name: cloudops-dashboard
    app.kubernetes.io/instance: staging
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: cloudops-platform
    app.kubernetes.io/managed-by: kubectl 